config/routes.rb
Rails.application.routes.draw do
  root to: 'foods#index'
  resources :foods
  get '/all' => 'foods#all'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  validates :morning, presence: true
  validates :noon, presence: true
  validates :night, presence: true
  validates :memo, length: { minimum: 0, maximum: 200 }
  validates :start_time, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @food = Food.find(params[:id])
  end

  def edit
    @food = Food.find(params[:id])
  end

  def update
    @food = Food.find(params[:id])
    if @food.update(food_params)
      redirect_to food_path(@food)
    else
      render :edit
    end
  end

  def destroy
    food = Food.find(params[:id])
    food.destroy
    redirect_to root_path
  end

  def all
    @foods = Food.all
  end

  private

  def food_params
    params.require(:food).permit(:morning, :noon, :night, :memo, :start_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/all.html.erb
<div class="container">
  <div class="row mt-4">
    <table>
      <tr>
        <th>日付</th>
        <th>朝食</th>
        <th>昼食</th>
        <th>夕食</th>
        <th>メモ</th>
        <th></th>
        <th></th>
      </tr>
      <% @foods.each do |food| %>
      <tr>
        <td class="pr-3 pb-1"><%= food.start_time.strftime("%Y年%m月%d日") %></td>
        <td class="pr-3 pb-1"><%= food.morning %></td>
        <td class="pr-3 pb-1"><%= food.noon %></td>
        <td class="pr-3 pb-1"><%= food.night %></td>
        <td class="pr-3 pb-1"><%= food.memo %></td>
        <td><%= link_to '編集', edit_food_path(food.id), class: "btn btn-outline-success mx-3" %></td>
        <td><%= link_to '削除', food_path(food), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-outline-success"  %></td>
      </tr>
      <% end %>
    </table>
  </div>
  <div class="row mt-3">
    <%= link_to 'カレンダーに戻る', foods_path, class: "btn btn-outline-success" %>
  </div>
</div>

app/views/foods/edit.html.erb
<div class="container">
  <div class="row my-3">
    <h3 class="border-success border-bottom">編集</h3>
  </div>
  <div class="row my-3">
    <% if @food.errors.any? %>
      <%= @food.errors.count %>件のエラーが発生しました
      <ul>
        <% @food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="row">
    <%= form_with model: @food, method: :patch do |f| %>

    <div class="time mb-2">
      <%= f.date_select :start_time %>
    </div>

    <div class="title mb-2">
      <%= f.text_field :morning, placeholder: "朝食" %>
    </div>

    <div class="content mb-2">
      <%= f.text_field :noon, placeholder: "昼食" %>
    </div>

    <div class="content mb-2">
      <%= f.text_field :night, placeholder: "夕食" %>
    </div>

    <div class="content mb-3">
      <%= f.text_area :memo, placeholder: "メモ" %>
    </div>

    <div class="submit">
      <%= f.submit "完了", class: "btn btn-outline-success" %>
    </div>

    <% end %>
  </div>
</div>

app/views/foods/index.html.erb
<div class="container">
  
  <div class="row my-1 mx-1">
    <%= month_calendar events: @foods do |date, foods| %>
      <%= date.day %>

      <% foods.each do |food| %>
        <div>
          <%= link_to food_path(food.id) do %>
            <i class="fa-solid fa-utensils"></i>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/foods/new.html.erb
<div class="container">
  <div class="row my-3">
    <h3 class="border-success border-bottom">追加</h3>
  </div>
  <div class="row my-3">
    <% if @food.errors.any? %>
      <%= @food.errors.count %>件のエラーが発生しました
      <ul>
        <% @food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="row">
    <%= form_with model: @food, url: foods_path do |f| %>

    <div class="time mb-2">
      <%= f.date_select :start_time %>
    </div>

    <div class="title mb-2">
      <%= f.text_field :morning, placeholder: "朝食" %>
    </div>

    <div class="content mb-2">
      <%= f.text_field :noon, placeholder: "昼食" %>
    </div>

    <div class="content mb-2">
      <%= f.text_field :night, placeholder: "夕食" %>
    </div>

    <div class="content mb-3">
      <%= f.text_area :memo, placeholder: "メモ" %>
    </div>

    <div class="submit">
      <%= f.submit "追加", class: "btn btn-outline-success" %>
      <%= link_to '戻る', root_path, class: "btn btn-outline-success"  %>
    </div>

    <% end %>
  </div>
</div>

app/views/foods/show.html.erb
<div class="container">
    <div class="row my-3 mx-3">
      <h5 class="border-success border-bottom"><%= @food.start_time.strftime("%Y年%m月%d日") %></h5>
    </div>
    <div class="row">
      <table>
        <tr>
          <th class="px-3 py-1">朝食</th>
          <td><%= @food.morning %></td>
        </tr>
        <tr>
          <th class="px-3 py-1">昼食</th>
          <td><%= @food.noon %></td>
        </tr>
        <tr>
          <th class="px-3 py-1">夕食</th>
          <td><%= @food.night %></td>
        </tr>
        <tr>
          <th class="px-3 py-1">メモ</th>
          <td><%= @food.memo %></td>
        </tr>
      </table>
    </div>

  <div class="row mt-5">
    <%= link_to '編集', edit_food_path(@food.id), class: "btn btn-outline-success mr-1" %>
    <%= link_to '削除', food_path(@food), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-outline-success mr-1"  %>
    <%= link_to '戻る', root_path, class: "btn btn-outline-success" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/521acb7552.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="mt-4">
    <h5>食事記録カレンダー</h5>
  </div>
  <div class="calendar-heading my-3">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= start_date.year %>年  <%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    <%= link_to new_food_path, class: "mx-3" do %>
      <i class="fa-regular fa-square-plus"></i>
    <% end %>
    <%= link_to '全て見る', all_path, class: "btn btn-outline-success" %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>